/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Scientific_Calculator;

import java.awt.Color;
import org.mariuszgromada.math.mxparser.*;
import java.lang.Object;
import java.awt.Toolkit;


/**
 *
 * @author dinhv
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Calculator() {
        initComponents();
        mXparser.setDegreesMode();
        btnDEG.setEnabled(false);
        btnDEG.setBackground(Color.white);
    }
    //Nếu kết quả là số nguyên thì hiển thị kiểu số nguyên 10.0 -> 10
    public String Songuyen(String result){
        int i=result.length();
        char a = result.charAt(i-1);
        char b = result.charAt(i-2);
        if(Character.toString(a).equals("0"))
            if(Character.toString(b).equals("."))
                result = result.substring(0, result.length() - 2);                     
        return result;
    }
    //Nếu kết quả là NaN thì hiển thị thông báo lỗi.
    public String CheckNaN(String result){
        if(result.equals("NaN")) result = "ERROR";
        return result;
    }
    public void check(){
        txtans.setText(x);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDongNgoac = new javax.swing.JButton();
        btnHEX = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        txtNhapvsKQ = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnLog10 = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        btnLoge = new javax.swing.JButton();
        btnCong = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        lbANS = new javax.swing.JLabel();
        btnTru = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        btnANS = new javax.swing.JButton();
        txtans = new javax.swing.JTextField();
        btnGTTD = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnMu = new javax.swing.JButton();
        btnGiaithua = new javax.swing.JButton();
        btne = new javax.swing.JButton();
        btnCan2 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnCham = new javax.swing.JButton();
        btnMoNgoac = new javax.swing.JButton();
        btnBIN = new javax.swing.JButton();
        btnCot = new javax.swing.JButton();
        btnOCT = new javax.swing.JButton();
        btnBang = new javax.swing.JButton();
        btnDEG = new javax.swing.JButton();
        btnRAD = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MÁY TÍNH KHOA HỌC by ĐINH VĨNH THÁI");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
        setName("mainFrame"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnDongNgoac.setBackground(new java.awt.Color(51, 51, 51));
        btnDongNgoac.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnDongNgoac.setForeground(new java.awt.Color(255, 255, 255));
        btnDongNgoac.setText(")");
        btnDongNgoac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDongNgoac.setFocusable(false);
        btnDongNgoac.setPreferredSize(new java.awt.Dimension(90, 50));
        btnDongNgoac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongNgoacActionPerformed(evt);
            }
        });

        btnHEX.setBackground(java.awt.Color.gray);
        btnHEX.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnHEX.setForeground(new java.awt.Color(255, 255, 255));
        btnHEX.setText("HEX");
        btnHEX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHEX.setFocusable(false);
        btnHEX.setPreferredSize(new java.awt.Dimension(90, 50));
        btnHEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHEXActionPerformed(evt);
            }
        });

        btnPi.setBackground(new java.awt.Color(51, 51, 51));
        btnPi.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnPi.setForeground(new java.awt.Color(255, 255, 255));
        btnPi.setText("π");
        btnPi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPi.setFocusable(false);
        btnPi.setPreferredSize(new java.awt.Dimension(90, 50));
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        txtNhapvsKQ.setEditable(false);
        txtNhapvsKQ.setBackground(new java.awt.Color(153, 153, 153));
        txtNhapvsKQ.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        txtNhapvsKQ.setForeground(new java.awt.Color(255, 255, 255));
        txtNhapvsKQ.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNhapvsKQ.setBorder(null);

        btn1.setBackground(new java.awt.Color(51, 51, 51));
        btn1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn1.setFocusable(false);
        btn1.setPreferredSize(new java.awt.Dimension(90, 50));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(51, 51, 51));
        btn2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn2.setFocusable(false);
        btn2.setPreferredSize(new java.awt.Dimension(90, 50));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(51, 51, 51));
        btn3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn3.setFocusable(false);
        btn3.setPreferredSize(new java.awt.Dimension(90, 50));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(51, 51, 51));
        btn4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn4.setFocusable(false);
        btn4.setPreferredSize(new java.awt.Dimension(90, 50));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(51, 51, 51));
        btn5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn5.setFocusable(false);
        btn5.setPreferredSize(new java.awt.Dimension(90, 50));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(51, 51, 51));
        btn6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn6.setFocusable(false);
        btn6.setPreferredSize(new java.awt.Dimension(90, 50));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(51, 51, 51));
        btn7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn7.setFocusable(false);
        btn7.setPreferredSize(new java.awt.Dimension(90, 50));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(51, 51, 51));
        btn0.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn0.setFocusable(false);
        btn0.setPreferredSize(new java.awt.Dimension(90, 50));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnLog10.setBackground(new java.awt.Color(51, 51, 51));
        btnLog10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLog10.setForeground(new java.awt.Color(255, 255, 255));
        btnLog10.setText("log(x)");
        btnLog10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLog10.setFocusable(false);
        btnLog10.setPreferredSize(new java.awt.Dimension(90, 50));
        btnLog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog10ActionPerformed(evt);
            }
        });

        btnDEL.setBackground(java.awt.Color.gray);
        btnDEL.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnDEL.setForeground(new java.awt.Color(255, 255, 255));
        btnDEL.setText("DEL");
        btnDEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDEL.setFocusable(false);
        btnDEL.setPreferredSize(new java.awt.Dimension(90, 50));
        btnDEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELActionPerformed(evt);
            }
        });

        btnLoge.setBackground(new java.awt.Color(51, 51, 51));
        btnLoge.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLoge.setForeground(new java.awt.Color(255, 255, 255));
        btnLoge.setText("ln(x)");
        btnLoge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLoge.setFocusable(false);
        btnLoge.setPreferredSize(new java.awt.Dimension(90, 50));
        btnLoge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogeActionPerformed(evt);
            }
        });

        btnCong.setBackground(new java.awt.Color(51, 51, 51));
        btnCong.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCong.setForeground(new java.awt.Color(255, 255, 255));
        btnCong.setText("+");
        btnCong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCong.setFocusable(false);
        btnCong.setPreferredSize(new java.awt.Dimension(90, 50));
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btnAC.setBackground(java.awt.Color.gray);
        btnAC.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnAC.setForeground(new java.awt.Color(255, 255, 255));
        btnAC.setText("AC");
        btnAC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAC.setFocusable(false);
        btnAC.setPreferredSize(new java.awt.Dimension(90, 50));
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        lbANS.setFont(new java.awt.Font("Arial Narrow", 1, 20)); // NOI18N
        lbANS.setForeground(new java.awt.Color(255, 255, 255));
        lbANS.setText("ANS");

        btnTru.setBackground(new java.awt.Color(51, 51, 51));
        btnTru.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnTru.setForeground(new java.awt.Color(255, 255, 255));
        btnTru.setText("-");
        btnTru.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTru.setFocusable(false);
        btnTru.setPreferredSize(new java.awt.Dimension(90, 50));
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(51, 51, 51));
        jButton19.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("%");
        jButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton19.setFocusable(false);
        jButton19.setPreferredSize(new java.awt.Dimension(90, 50));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        btnANS.setBackground(new java.awt.Color(51, 51, 51));
        btnANS.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnANS.setForeground(new java.awt.Color(255, 255, 255));
        btnANS.setText("ANS");
        btnANS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnANS.setFocusable(false);
        btnANS.setPreferredSize(new java.awt.Dimension(90, 50));
        btnANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnANSActionPerformed(evt);
            }
        });

        txtans.setEditable(false);
        txtans.setBackground(new java.awt.Color(102, 102, 102));
        txtans.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        txtans.setForeground(new java.awt.Color(255, 255, 255));
        txtans.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnGTTD.setBackground(new java.awt.Color(51, 51, 51));
        btnGTTD.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGTTD.setForeground(new java.awt.Color(255, 255, 255));
        btnGTTD.setText("x/y");
        btnGTTD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGTTD.setFocusable(false);
        btnGTTD.setPreferredSize(new java.awt.Dimension(90, 50));
        btnGTTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGTTDActionPerformed(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(51, 51, 51));
        btnCos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCos.setForeground(new java.awt.Color(255, 255, 255));
        btnCos.setText("cos(x)");
        btnCos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCos.setFocusable(false);
        btnCos.setPreferredSize(new java.awt.Dimension(90, 50));
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        jButton37.setBackground(java.awt.Color.gray);
        jButton37.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("EXIT");
        jButton37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton37.setFocusable(false);
        jButton37.setPreferredSize(new java.awt.Dimension(90, 50));
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        btnChia.setBackground(new java.awt.Color(51, 51, 51));
        btnChia.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnChia.setForeground(new java.awt.Color(255, 255, 255));
        btnChia.setText("÷");
        btnChia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnChia.setFocusable(false);
        btnChia.setPreferredSize(new java.awt.Dimension(90, 50));
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });

        btnTan.setBackground(new java.awt.Color(51, 51, 51));
        btnTan.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnTan.setForeground(new java.awt.Color(255, 255, 255));
        btnTan.setText("tan(x)");
        btnTan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTan.setFocusable(false);
        btnTan.setPreferredSize(new java.awt.Dimension(90, 50));
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnMu.setBackground(new java.awt.Color(51, 51, 51));
        btnMu.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnMu.setForeground(new java.awt.Color(255, 255, 255));
        btnMu.setText("x^y");
        btnMu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMu.setFocusable(false);
        btnMu.setPreferredSize(new java.awt.Dimension(90, 50));
        btnMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuActionPerformed(evt);
            }
        });

        btnGiaithua.setBackground(new java.awt.Color(51, 51, 51));
        btnGiaithua.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnGiaithua.setForeground(new java.awt.Color(255, 255, 255));
        btnGiaithua.setText("x!");
        btnGiaithua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGiaithua.setFocusable(false);
        btnGiaithua.setPreferredSize(new java.awt.Dimension(90, 50));
        btnGiaithua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaithuaActionPerformed(evt);
            }
        });

        btne.setBackground(new java.awt.Color(51, 51, 51));
        btne.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btne.setForeground(new java.awt.Color(255, 255, 255));
        btne.setText("e");
        btne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btne.setFocusable(false);
        btne.setPreferredSize(new java.awt.Dimension(90, 50));
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });

        btnCan2.setBackground(new java.awt.Color(51, 51, 51));
        btnCan2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCan2.setForeground(new java.awt.Color(255, 255, 255));
        btnCan2.setText("√(x)");
        btnCan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCan2.setFocusable(false);
        btnCan2.setMaximumSize(new java.awt.Dimension(100, 100));
        btnCan2.setPreferredSize(new java.awt.Dimension(90, 50));
        btnCan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCan2ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(51, 51, 51));
        btn8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn8.setFocusable(false);
        btn8.setPreferredSize(new java.awt.Dimension(90, 50));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnSin.setBackground(new java.awt.Color(51, 51, 51));
        btnSin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnSin.setForeground(new java.awt.Color(255, 255, 255));
        btnSin.setText("sin(x)");
        btnSin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSin.setFocusable(false);
        btnSin.setPreferredSize(new java.awt.Dimension(90, 50));
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(51, 51, 51));
        btn9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn9.setFocusable(false);
        btn9.setPreferredSize(new java.awt.Dimension(90, 50));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnCham.setBackground(new java.awt.Color(51, 51, 51));
        btnCham.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        btnCham.setForeground(new java.awt.Color(255, 255, 255));
        btnCham.setText(".");
        btnCham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCham.setFocusable(false);
        btnCham.setPreferredSize(new java.awt.Dimension(90, 50));
        btnCham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamActionPerformed(evt);
            }
        });

        btnMoNgoac.setBackground(new java.awt.Color(51, 51, 51));
        btnMoNgoac.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnMoNgoac.setForeground(new java.awt.Color(255, 255, 255));
        btnMoNgoac.setText("(");
        btnMoNgoac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMoNgoac.setFocusable(false);
        btnMoNgoac.setPreferredSize(new java.awt.Dimension(90, 50));
        btnMoNgoac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoNgoacActionPerformed(evt);
            }
        });

        btnBIN.setBackground(java.awt.Color.gray);
        btnBIN.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnBIN.setForeground(new java.awt.Color(255, 255, 255));
        btnBIN.setText("BIN");
        btnBIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBIN.setFocusable(false);
        btnBIN.setPreferredSize(new java.awt.Dimension(90, 50));
        btnBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBINActionPerformed(evt);
            }
        });

        btnCot.setBackground(new java.awt.Color(51, 51, 51));
        btnCot.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnCot.setForeground(new java.awt.Color(255, 255, 255));
        btnCot.setText("cot(x)");
        btnCot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCot.setFocusable(false);
        btnCot.setPreferredSize(new java.awt.Dimension(90, 50));
        btnCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCotActionPerformed(evt);
            }
        });

        btnOCT.setBackground(java.awt.Color.gray);
        btnOCT.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnOCT.setForeground(new java.awt.Color(255, 255, 255));
        btnOCT.setText("OCT");
        btnOCT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnOCT.setFocusable(false);
        btnOCT.setPreferredSize(new java.awt.Dimension(90, 50));
        btnOCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOCTActionPerformed(evt);
            }
        });

        btnBang.setBackground(java.awt.Color.gray);
        btnBang.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btnBang.setForeground(new java.awt.Color(255, 255, 255));
        btnBang.setText("=");
        btnBang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBang.setFocusable(false);
        btnBang.setPreferredSize(new java.awt.Dimension(90, 50));
        btnBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangActionPerformed(evt);
            }
        });

        btnDEG.setBackground(new java.awt.Color(0, 0, 0));
        btnDEG.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnDEG.setForeground(new java.awt.Color(255, 255, 255));
        btnDEG.setText("DEG");
        btnDEG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnDEG.setFocusable(false);
        btnDEG.setPreferredSize(new java.awt.Dimension(90, 50));
        btnDEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEGActionPerformed(evt);
            }
        });

        btnRAD.setBackground(new java.awt.Color(0, 0, 0));
        btnRAD.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnRAD.setForeground(new java.awt.Color(255, 255, 255));
        btnRAD.setText("RAD");
        btnRAD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRAD.setFocusable(false);
        btnRAD.setPreferredSize(new java.awt.Dimension(90, 50));
        btnRAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRADActionPerformed(evt);
            }
        });

        btnNhan.setBackground(new java.awt.Color(51, 51, 51));
        btnNhan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnNhan.setText("×");
        btnNhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNhan.setFocusable(false);
        btnNhan.setPreferredSize(new java.awt.Dimension(90, 50));
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnCham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnANS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnBang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnChia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnGiaithua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnCan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnGTTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnCot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnDEG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLog10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoge, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnOCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnHEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMoNgoac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnDongNgoac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbANS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtans, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtNhapvsKQ)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtNhapvsKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbANS)
                    .addComponent(txtans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDEG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLog10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMoNgoac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDongNgoac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGiaithua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGTTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnChia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnANS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String ans = "0"; //Kết quả phép tính trước
    String ans_text = ""; //Nội dung phép tính trước
    String x = ""; //Chuỗi được dùng để tính toán
    String ans_x_text = "";
    
    private void btnMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"^");
        x = x.concat("^");
    }//GEN-LAST:event_btnMuActionPerformed

    private void btnGiaithuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaithuaActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"!");
        x = x.concat("!");
    }//GEN-LAST:event_btnGiaithuaActionPerformed

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"e");
        x = x.concat("e");
    }//GEN-LAST:event_btneActionPerformed

    private void btnCan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCan2ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"sqrt(");
        x = x.concat("sqrt(");
    }//GEN-LAST:event_btnCan2ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"8");
        x = x.concat("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"sin(");
        x = x.concat("sin(");
    }//GEN-LAST:event_btnSinActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"9");
        x = x.concat("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnChamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+".");
        x = x.concat(".");
    }//GEN-LAST:event_btnChamActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"0");
        x = x.concat("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELActionPerformed
        // TODO add your handling code here:
        String m = txtNhapvsKQ.getText();
        String n = x;
        txtNhapvsKQ.setText("");
        x = "";
        for(int i=0;i<m.length()-1;i++){
            txtNhapvsKQ.setText(txtNhapvsKQ.getText()+m.charAt(i)); //xoa 1 ki tu o textbox
            x = x + n.charAt(i); //xoa 1 ki tu o chuoi x        
        }
    }//GEN-LAST:event_btnDELActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"+");
        x = x.concat("+");
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText("");
        x = "";
    }//GEN-LAST:event_btnACActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"-");
        x = x.concat("-");
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnANSActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"Ans");
        x = x.concat(ans);
    }//GEN-LAST:event_btnANSActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"cos(");
        x = x.concat("cos(");
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"÷");
        x = x.concat("/");
    }//GEN-LAST:event_btnChiaActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"tan(");
        x = x.concat("tan(");
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnMoNgoacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoNgoacActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"(");
        x = x.concat("(");
    }//GEN-LAST:event_btnMoNgoacActionPerformed

    private void btnCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"cot(");
        x = x.concat("cot(");
    }//GEN-LAST:event_btnCotActionPerformed

    private void btnDongNgoacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongNgoacActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+")");
        x = x.concat(")");
    }//GEN-LAST:event_btnDongNgoacActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"π");
        x = x.concat("pi");
    }//GEN-LAST:event_btnPiActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"1");
        x = x.concat("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"2");
        x = x.concat("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"3");
        x = x.concat("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"4");
        x = x.concat("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"5");
        x = x.concat("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"6");
        x = x.concat("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"7");
        x = x.concat("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnLog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog10ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"log(");
        x = x.concat("log10(");
    }//GEN-LAST:event_btnLog10ActionPerformed

    private void btnLogeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogeActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"ln(");
        x = x.concat("ln(");
    }//GEN-LAST:event_btnLogeActionPerformed
    
    private void btnBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangActionPerformed
        ans_text = txtNhapvsKQ.getText();
        Expression e = new Expression(x);//ta lấy dữ liệu từ x thay thì textbox
        double v = e.calculate();
        String result = CheckNaN(Double.toString(v));             
        ans = Songuyen(result);
        ans_x_text = x;
        x = ans;
        txtNhapvsKQ.setText(ans);//in ket qua ra text box
        txtans.setText(ans_text);
    }//GEN-LAST:event_btnBangActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"%");
        x = x + "%";
    }//GEN-LAST:event_jButton19ActionPerformed

    private void btnGTTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGTTDActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"/");        
        x = x + "/";
    }//GEN-LAST:event_btnGTTDActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        System.exit(0);        
    }//GEN-LAST:event_jButton37ActionPerformed

    private void btnBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBINActionPerformed
        // TODO add your handling code here:
        ans_text = txtNhapvsKQ.getText();
        try
        {
            int n = Integer.parseInt(txtNhapvsKQ.getText());
            txtNhapvsKQ.setText(ans_text+"==>"+Integer.toBinaryString(n)+" (bin)");
            ans = ans_text;
            txtans.setText(ans_text);

        }
        catch(Exception e){
            txtNhapvsKQ.setText("Error!!!");
        }
    }//GEN-LAST:event_btnBINActionPerformed

    private void btnOCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOCTActionPerformed
        // TODO add your handling code here:
        ans_text = txtNhapvsKQ.getText();
        try
        {
            int n = Integer.parseInt(txtNhapvsKQ.getText());
            txtNhapvsKQ.setText(ans_text+"==>"+Integer.toOctalString(n)+" (oct)");
            ans = ans_text;
            txtans.setText(ans_text);

        }
        catch(Exception e){
            txtNhapvsKQ.setText("Error!!!");
        }
    }//GEN-LAST:event_btnOCTActionPerformed

    private void btnHEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHEXActionPerformed
        // TODO add your handling code here:
        ans_text = txtNhapvsKQ.getText();
        try
        {
            int n = Integer.parseInt(txtNhapvsKQ.getText());
            txtNhapvsKQ.setText(ans_text+"==>"+Integer.toHexString(n)+" (hex)");
            ans = ans_text;
            txtans.setText(ans_text);

        }
        catch(Exception e){
            txtNhapvsKQ.setText("Error!!!");
        }
    }//GEN-LAST:event_btnHEXActionPerformed

    private void btnDEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEGActionPerformed
        // TODO add your handling code here:
        mXparser.setDegreesMode();
        btnDEG.setBackground(Color.white);
        btnRAD.setBackground(Color.black);
        btnDEG.setEnabled(false);
        btnRAD.setEnabled(true);
        if(txtans.getText().equals("")||txtNhapvsKQ.getText().equals("")) return;
        else {
        Expression e = new Expression(ans_x_text);
        double v = e.calculate();        
        txtNhapvsKQ.setText(Songuyen(Double.toString(v)));
        }
    }//GEN-LAST:event_btnDEGActionPerformed

    private void btnRADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRADActionPerformed
        // TODO add your handling code here:
        mXparser.setRadiansMode();
        btnDEG.setBackground(Color.black);
        btnRAD.setBackground(Color.white);
        btnDEG.setEnabled(true);
        btnRAD.setEnabled(false); 
        if(txtans.getText().equals("")||txtNhapvsKQ.getText().equals("")) return;
        else {
        Expression e = new Expression(ans_x_text);
        double v = e.calculate();
        txtNhapvsKQ.setText(Songuyen(Double.toString(v)));       
        }
    }//GEN-LAST:event_btnRADActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
        // TODO add your handling code here:
        txtNhapvsKQ.setText(txtNhapvsKQ.getText()+"×");
        x = x.concat("*");
    }//GEN-LAST:event_btnNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnANS;
    private javax.swing.JButton btnBIN;
    private javax.swing.JButton btnBang;
    private javax.swing.JButton btnCan2;
    private javax.swing.JButton btnCham;
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCot;
    private javax.swing.JButton btnDEG;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDongNgoac;
    private javax.swing.JButton btnGTTD;
    private javax.swing.JButton btnGiaithua;
    private javax.swing.JButton btnHEX;
    private javax.swing.JButton btnLog10;
    private javax.swing.JButton btnLoge;
    private javax.swing.JButton btnMoNgoac;
    private javax.swing.JButton btnMu;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnOCT;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnRAD;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btne;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbANS;
    private javax.swing.JTextField txtNhapvsKQ;
    private javax.swing.JTextField txtans;
    // End of variables declaration//GEN-END:variables
  
}
